### ISSUE TITLE
Where should we chat?

### ISSUE THREAD

**Issue by vongohren** [din-ssi/wallet#4]
Tire of email so doing it here

Mariuz: 'Rant against slack --

I’m a bit “biased” against Microsoft - I mean I love their work in SSI 😉 But, their tools, like Slack and Teams are honestly mind-f***ing and I never understand the logic. For example, in Slack, the messages get “hidden” (rolled in) and you need to keep click on things to “unroll” the communication in order to catch up – I cannot easily do quick text search etc (I admit, I have not invested a lot of time on HOW to achieve those trivial things, but, I assume those should be trivial) – anyway, it may work with some people, but it does not work with me – when I go to a channel I just want to scroll and catch up on what has been discussed. So I would prefer to keep the Bachelor discussions on Discord, if possible, and given that Jonas is already on Discord DIN, why not just use that? Something that needs to be communicated to broader DIN community through Slack I’m sure can be done also in addition, but, to day-to-day project sync, Discord would work better with me tbh. 

But, I will go happily with the majority 😉

I like Discourse, but, for streamlining work here, I think we need four components:

* Code. Git is the only way to deal with it, and, issue tracker is the way to discuss code, make decisions, and report things. ß Github + Git
* Static documentation, like the onboarding Wiki page for new students, as I have suggested.  It is not to be “discussed”, but, it is to be “read” – in a form of manual, or static links. We could use something more structured, like coda.io for it, or a plain wiki, or like we do now, a Google Doc.
* Place to document structured discussions and to make decisions (discourse would fit great, but, so would Issue tracker on Github, I’ve used it almost like discourse – top level discussion issues + follow up comments.
* Chat for just chatting (Slack, Discord, e-mail (not great))'

'

DIN will be on slack because of the broader community.
I dont mind doing doable but im mindful that we dont have to have that much filtering outwards. We are still young in this space and I would love for faster communication and not that much filter. Meaning one place to discuss allows others to join in on the conversation eearlier, if curious

**Comment by gtl-hig** [comment]
I understand the point, and I also prefer one place vs. multiple places. However, we have two relatively non-overlapping objectives here --> 

One: high-level discussions, strategic decisions, broader community involvement, discussing other, related activities, projects, funding, coordination, etc. This is where DIN fits in, and, I agree, all those discussions should be done in one place with a broader community easily able to jump in (ie. Slack). 

Two: coordinating this single particular bachelor project, identifying/discussing low level, mostly technical tasks, coordinating about bugs/issues, coordinating administrative duties and tasks with NTNU, etc. This should be rather "private" and constrained to the project only, because we want this to be quite focused. 

We could merge ONE and TWO into single "venue", but, I feel they serve two different purposes and do not necessarily mix.  For example high-level strategic discussions are usually non-conductive to low-level code production ;) 
For one, I would like to use git-hooks and GitHub webhooks to feed notification to the a "chat" platform, such that I can quickly browse through and get updates (see #6). How relevant is that to a broader DIN community?  I think it isn't, but, it is relevant directly to people working on THIS project, so, in that sense for example, perhaps it makes sense to isolate these two?

**Comment by vongohren** [comment]
I agree, in all you are saying.
I just think that private versus public channels, can solve that issue
We will keep seperations on things, im just in for one platform where we can move things simpler than other things. As DIN will grow, and if we network with one guy and he wants to join, he will have to add discord to his flow. Instead of just invited into the private channel of the project

And for your latest comment, yes I agree again. But that is where private versus public comes in in my mind. Instead of seperating at level 1, we can seperate at level 2 but making it easier to transition between level1 and 2. Mostly the other way around

**Comment by Arxcis** [comment]
As a developer, what I need from a chat app, is to host meetings. 

Other than that, I would like to stay away from the chat apps as much as possible, and do most discussions on github, since most chat apps are a data-silos, which are difficult to reference from the rest of the web.

I do have a preference for chat apps with a strong privacy and encryption guarantee (example: Signal), but I am also ok with using Slack, or Discord, or Teams, or whatever the kids use these days. Whatever gets the meeting done.

**Comment by vongohren** [comment]
Sounds good. We also need to think about where we can reply and be accessible. For me slack is first then discord, in terms of accessibility.

But discord do have integrated meeting opportuinites, which is nice.

Im a bit up in the air on this. DIN will be moving to slack to cater to a broader aspect of people. The business and normal working people, not gamers or developers. That is why I use that as an option. I was the first suggestion Discord for DIN, but it was not that easy to build a community around it. Because people were not using it as their go to tool, the use slack, for work and other things.

So for now we are hanging out on the din discord. Until DIN move we will probably do nothing about it. 
But we still need to decide on what org we work under, see #3

**Comment by vongohren** [comment]
Just reverberating what was said in last bump email: "As for chat, I dont care. DIN in itself will focus much more on slack for the next coming months, and Im there everyday anyways. Im haning on discord but have some slower response time and keep forgetting things there. So this comes down to a bit to Jonas, what is your strongest wish? "

**Comment by gtl-hig** [comment]
I propose @vongohren "close" officially DIN on Discord and kicks out everyone not related to the ongoing development. Then grant me and @Arxcis admin permissions on the server, such that we can hook-up webhooks from GitHub, and, for dev related CHAT we use existing DIN on Discord. We can setup "admin" role for people that can manage and organise necessary channels there, and we just continue using DIN Discord for the purpose of DEV chat.

**Comment by Arxcis** [comment]
Sounds reasonable:
- DIN Discord for developers
- DIN Slack for everyone else

**Comment by abylays** [comment]
I use both Slack and Discord. So leaving Discord for Bachelor project and Slack for DIN public works for me. We can create specific channels for Dev projects in Slack also, so we will just be announcing our results and progress for other DIN members

**Comment by vongohren** [comment]
Discord it is!

**Comment by vongohren** [comment]
Will prune soon, but then @Arxcis you need to join so we can give you rights. @abylays @gtl-hig you have admin roles, did not check right now if it has all the rights it needs though

**Comment by Arxcis** [comment]
Here is my Discord-tag: jonasjso#5332. I will need an invite to be able to join.

**Comment by vongohren** [comment]
@Arxcis heres a link: https://discord.gg/2WGpa9b

**Comment by gtl-hig** [comment]
Thanks @vongohren - things seems to work fine on Discord. I'll setup a web hook for GitHub once a decision is made if we stay here or move to Din-Foundation.
